### ISSUE TITLE
Remove `$OWD`

### ISSUE THREAD

**Issue by TheAssassin** [AppImage/appimagetool#16]
I have not once seen anybody use the `$OWD` environment variable. Its purpose is unclear to me anyway. I think we should just remove it.

**Comment by probonopd** [comment]
https://docs.appimage.org/packaging-guide/environment-variables.html

> * OWD: Path to working directory at the time the AppImage is called

It was introduced upon request from @jviotti and the Scribus team. It is documented and in active use, as a quick [search](https://github.com/search?q=AppImage+%22OWD%22&type=code) shows.

Background:

As you know, some applications (especially ones for which there is no source code available) need to be patched so that the absolute `/usr` is replaced with a relative `././`. This then requires an `AppRun` that does `cd "{HERE}/usr"` prior to running the payload application.
Once the payload application is running, it can cd back to the original working directory (OWD), like e.g.,

https://github.com/vim/vim-appimage/blob/b1e366d90a204c3b5554fce6ceed6fbe1f579adf/scripts/vim.start.sh#L18-L21

does.

Let's not remove it, it would break existing AppImage builds.

Reference:
* https://github.com/AppImage/AppImageKit/issues/172
* [Expanation in the FreeCAD forum](https://forum.freecad.org/viewtopic.php?style=10&p=186899&sid=1e310245c1d52544bc02d6f9a37221a0#p186899)
