### ISSUE TITLE
appimagetool `--version` is not output to stdout

### ISSUE THREAD

**Issue by brunvonlope** [AppImage/appimagetool#88]
If I try to use the output of appimagetool as the value of some variable in bash, it will not work:

![image](https://github.com/user-attachments/assets/9d59b1c2-9d7d-4946-84ad-64cfbd2a57bf)

As the screenshot shows, $my_var seems to be empty

**Comment by Samueru-sama** [comment]
That would be because appimagetool is outputting to stderr instead: 

![image](https://github.com/user-attachments/assets/56dcfea1-f9ec-4938-aa30-a4f385f30a89)

And yeah this should not happen given that isn't an error message.

**Comment by brunvonlope** [comment]
@Samueru-sama Indeed. The error output is being caused by this line:

https://github.com/AppImage/appimagetool/blob/4d44730d6117856cb357bdeacf65a636f3bd9d74/src/appimagetool.c#L614

@TheAssassin Is this deliberate?

**Comment by brunvonlope** [comment]
Similarly, the runtiime outputs appimage-version to stderr:

https://github.com/AppImage/type2-runtime/blob/f6c0b18d42eb4aa629cc6a18d08c20cc67c80af8/src/runtime/runtime.c#L1523

So, probably there is a reason for this or it is a coincidence.

**Comment by TheAssassin** [comment]
Please don't ping people just 10 minutes after creating an issue, it's a coincidence I was looking at my emails right now. It's not very polite.

First of all, the title of the issue is misleading. You could easily read stderr from your shell as well.

As to whether it makes sense to output the version number on stderr, I'm not sure why that is. I guess we can just change it to stderr. I'm not sure why anybody would want to store the version number and potentially parse it, it's not meant to be machine readable and might change any time.

**Comment by brunvonlope** [comment]
> Please don't ping people

@ is not a pinging feature per se. In my comment there is text specially directed to you. I use @ to make clear who I am directing the message, that's it.

> First of all, the title of the issue is misleading

From my point of view, Samueru confirmed that what is happening is litereally what is written in the issue (at least for --version). If the title is too broad you can just change it as a developer, that's how a bug tracker works. No need for bombing the issue.

---

As for the rest of your comment is still unclear why a non error is being output for stderr. It's unorthorox to say the least. 

So, about what the appimage users will do with that output... I will use it to log appimage tool version in the beggining of a script, way before calling the tool for squashing in the same script. Anyway, I don't think it is of your business...

**Comment by TheAssassin** [comment]
> As for the rest of your comment is still unclear why a non error is being output for stderr. It's unorthorox to say the least.

That again is wrong. Messages directed to the user (especially logging) is printed on stderr _by default_ in the _vast majority_ of all tools and logging libraries. The only difference here is that with `--version`, one could classify the specific output as the result of the process and that should be printed on stdout. Debug messages illustrating, e.g., how the message was composed should not be printed on stdout.

Java's `-version` has been printed on stderr ever since, and I think Python up to version 3 also did that. There are plenty more examples. Again, the only reason not to print the version number on stderr in this specific case is that it's the expected result of the process.

**Comment by brunvonlope** [comment]
Oh, got it. That's a fair point. I am used to 'flatpak-builder --version', 'clang --version' etc., which output to stdout.

**Comment by TheAssassin** [comment]
> Anyway, I don't think it is of your business...

I don't give anything about what you want to do with the output. I warned you it's not meant for parsing. That's all. You don't use it that way. Works for me.

Your rude tone is not just unnecessary, it's quite demotivating. I didn't mean to attack you with my comment. It did seem impatient to me. Been there many times, I maintain a lot of projects.

> If the title is too broad

The point is, you claim it can "NOT" be evaluated. But adding a `2>&1` inside your subshell "fixes" your specific problem. @Samueru-sama didn't confirm your specific issue (I guess it could be read that way, but I don't think they intended to imply that), they explained to you that your expectation of it being printed on stdout is wrong. With the information that it's printed on stderr, you could have fixed your script to read from stderr using the redirection feature.

The rest of my comment is discussing the pro and con of the change. There's a point both in using stdout and stderr. We need to discuss that, obviously. What if people use the output already and changing to stderr breaks their script then? This needs to be taken into account.

**Comment by brunvonlope** [comment]
About my tone, I must say that your first welcome message  caught me completely off guard, sounded like a dropkick to me, but it leads to the point of my pinging and so on indefinitely. So, I'll end the discussion with an apology about my last sentence. **Sorry**.

I won't use @ anymore in this tracker. Discussion will be a bit obscure because GH doesn't have the reply feature like GL and that requires referencing past texts as I did above but at least it avoids friction.

And, I'm fine with the redirection trick (I just didn't thought about it, otherwise the issue title would be obviously different), so let's close as expected behavior.

**Comment by Samueru-sama** [comment]
I don't think outputting version to stderr is right since it is not an error message. I also can't think of a scenario where changing this would break something, given that running `--version` without redirecting stderr produces an empty result. 

Now had `--version` put some output in both stderr and stdout before then yeah it is possible that this is being used in a way that changing the output would break something.

**Comment by TheAssassin** [comment]
Let's change it then. I suppose we can just say that nobody _should_ parse the info anyway, so we can change it any time.
