### ISSUE TITLE
Bundle static versions of desktop-file-validate and zsyncmake

### ISSUE THREAD

**Issue by probonopd** [AppImage/appimagetool#9]
To maintain drop-in compatibility, we also need to ship like we did in AppImageKit's `appimagetool`:

* `usr/bin/desktop-file-validate`
* `usr/bin/zsyncmake`

(fwiw, https://github.com/probonopd/static-tools/releases/tag/continuous has those, built statically on Alpine Linux.)

**Comment by TheAssassin** [comment]
We should consider making zsync2 a core project again. Then we could utilize `libzsync2` directly instead of having to build and ship separate tools.

**Comment by probonopd** [comment]
> utilize libzsync2

Maybe after 1.0

**Comment by TheAssassin** [comment]
Since we want to make this repository be as self-contained as possible (except for AppImage core projects), I'll add build scripts for these inspired by the code in your repository just as we've done for mksquashfs. This is going to increase the build times slightly for now, but that is acceptable to me.

Is there a library for checking desktop entries, too?

**Comment by probonopd** [comment]
Agree on making this repo as self-contained as possible (except for AppImage core projects). Mentioned _static-tools_ only as a reference in case it is helpful. 

I don't know a library for checking desktop entries but it shouldn't be all too hard to convert
https://gitlab.freedesktop.org/xdg/desktop-file-utils/-/blob/master/src/validate.c
into one.

**Comment by rodlie** [comment]
Would appreciate if you removed the need for ``desktop-file-validate``, I upgraded appimagetool on my build server today and my build broke due to this (yes, my previous appimagetool was old, 2023-03-08, btw why have you wiped the git history?).

For various reasons I won't discuss I'm unable install ``desktop-file-validate``, so I had to make a dummy file to work around this.

**Comment by ivan-hc** [comment]
Hi, I saw there's a PR pending for four months here.

I noticed that to use the new appimagetool we need to install "desktop-file-utils" so I come here in this repo and I've found this opened issue.

Any news?

**Comment by probonopd** [comment]
Waiting on @TheAssassin.
